squashed consolidate commit
gitignore

move examples into streaming folder

move sourcev2 example into right folder. does not compile

big move + proto compile

move to correct packages

import FixedHeaderProvider

add autovalue to pom

compiles

tests compile

add vscode files to gitignore

fix example pipeline

builds

revert flink-examples-streaming-gcp-pubsub pom

java.lang.NoClassDefFoundError: org/apache/flink/shaded/io/netty/channel/ChannelFactory

pipeline works